name: Delete Old Workflows

on:
  schedule:
    - cron: '0 1 * * *'  # 每天1点执行
  repository_dispatch:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 7
        keep_minimum_runs: 0

    - name: Delete Old Releases
      run: |
        # 获取8天前的日期
        EIGHT_DAYS_AGO=$(date -d '8 days ago' +"%Y-%m-%d")
        
        # 列出8天前的标签并删除
        git tag -l | grep -E "^v[0-9]+\.[0-9]+\.[0-9]+$" | while read -r TAG; do
          TAG_DATE=$(git log -1 --format=%ai "$TAG" | awk '{print $1}')
          if [[ "$TAG_DATE" < "$EIGHT_DAYS_AGO" ]]; then
            git push --delete origin "$TAG"
            git tag -d "$TAG"
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
