name: Daily Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: 50 17 * * *

env:
  UPLOAD_RELEASE: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Cleaning:
    runs-on: ubuntu-22.04

    steps:
    - name: 删除旧的工作流
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 0
        keep_minimum_runs: 1


    - name: 删除自动发布的旧固件
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 3
        delete_tags: true
