name: Daily Cleanup

on:
  repository_dispatch:
  workflow_dispatch:
  
env:
  UPLOAD_RELEASE: true
  
jobs:
  Cleaning:
    runs-on: ubuntu-22.04

    steps:

    - name: 删除运行记录
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
        token: ${{ env.GITHUB_TOKEN }}

    - name: 删除自动发布的旧固件
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 4
        delete_tags: true
